table dim_employees
	lineageTag: 8615c1ab-1188-420e-839f-7476c665b4fc

	column Age
		dataType: string
		lineageTag: 758897bd-ad77-4bb0-8868-714f9790da02
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column JoinDate
		dataType: string
		lineageTag: 693d5bbb-b9ab-48db-8704-e86174dde663
		summarizeBy: none
		sourceColumn: JoinDate

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: string
		lineageTag: 7bd37b9f-f969-4e82-a840-3f0cfc86f548
		summarizeBy: none
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 4057cb94-5f0e-468b-ab37-16f9237db558
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 7da50215-d3b2-46f0-9f88-3ab7861a0568
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Tenure
		dataType: double
		lineageTag: d9b3b820-1a76-4caa-8f2f-906ae5d938b9
		summarizeBy: none
		sourceColumn: Tenure

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FirstName
		dataType: string
		lineageTag: e7530dd3-458b-40b2-9608-30c64cf0cd45
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 30b1f7e4-8308-4bf0-90bb-13e190430b1f
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6bd53ff4-b60a-41c0-a54b-aee505b1ea8a
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column IsManager
		dataType: string
		lineageTag: 190d586b-4e56-483b-afa2-fea59f2031fb
		summarizeBy: none
		sourceColumn: IsManager

		annotation SummarizationSetBy = Automatic

	column PK_Employee
		dataType: string
		isHidden
		isKey
		lineageTag: 038270cb-c3d0-4e36-b35b-9727139f7bb5
		summarizeBy: none
		sourceColumn: PK_Employee

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employee
		dataType: string
		lineageTag: ea730e29-619a-412a-a2b5-6556a2d7c8c1
		summarizeBy: none
		sourceColumn: Employee

		annotation SummarizationSetBy = Automatic

	column PK_Store
		dataType: string
		isHidden
		lineageTag: dca067a4-f582-4e5a-bec4-f52a049ca450
		summarizeBy: none
		sourceColumn: PK_Store

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: 651be6dc-2512-43dd-8f0c-410c377213ce
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	partition dim_employees = m
		mode: import
		source =
				let
				    Path = Path,
				    FileName = "dim_employees.csv",
				    PathComplete = Path & FileName,
				    Source = Csv.Document(File.Contents(PathComplete), [Delimiter = ",", Encoding = 1252, QuoteStyle = QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    FilteredActive = Table.SelectRows(PromotedHeaders, each [Active] = "TRUE"),
				    AddedTenure = Table.AddColumn(FilteredActive, "Tenure", each Duration.Days(Date.From(DateTime.LocalNow()) - Date.FromText([JoinDate])) / 365, type number),
				    ExtractedFirstName = Table.AddColumn(AddedTenure, "FirstName", each Text.BeforeDelimiter([Employee], " "), type text),
				    ExtractedLastName = Table.AddColumn(ExtractedFirstName, "LastName", each Text.AfterDelimiter([Employee], " "), type text),
				    MergedStores = Table.NestedJoin(ExtractedLastName, {"PK_Store"}, dim_stores, {"PK_Store"}, "StoreInfo", JoinKind.LeftOuter),
				    ExpandedCity = Table.ExpandTableColumn(MergedStores, "StoreInfo", {"City"}, {"City"}),
				    #"Sorted Rows" = Table.Sort(ExpandedCity,{{"PK_Store", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

