table dim_stores
	lineageTag: 93c7ef66-47d7-410a-8149-55ccca940722

	column StoreID
		dataType: string
		lineageTag: bdfd41ee-f18b-4a5f-8a85-ab72cd82be95
		summarizeBy: none
		sourceColumn: StoreID

		annotation SummarizationSetBy = Automatic

	column StoreName
		dataType: string
		lineageTag: db6b06a1-4ae2-46d6-b79e-2724d888ad5b
		summarizeBy: none
		sourceColumn: StoreName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 4e426408-2997-4eae-b677-ba9701e55970
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Lat
		dataType: string
		lineageTag: 61a5e44a-0d3e-41e0-b746-41b5889fc13a
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: Lat

		annotation SummarizationSetBy = Automatic

	column Long
		dataType: string
		lineageTag: af68d169-8ceb-4839-9040-77222ce592a9
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: Long

		annotation SummarizationSetBy = Automatic

	partition dim_stores = m
		mode: import
		source =
				let
				    Path = Path,
				    FileName = "dim_stores.csv",
				    PathComplete = Path & FileName,
				    Source = Csv.Document(File.Contents(PathComplete),[Delimiter=",", Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

